<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-M54PCD3" name="Running Regression for dashboard tests" tests="6" failures="2" timestamp="16 Sep 2019 12:41:39 GMT" time="244.254" errors="0">
  <testcase name="@AfterTest teardown" time="0.0" classname="Dashboard_Tests.Login_DataDriven_Through_DataProvider_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Dashboard_Tests.Login_DataDriven_Through_DataProvider_Test.teardown(Login_DataDriven_Through_DataProvider_Test.java:45)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest teardown -->
  <testcase name="forgot_Password" time="55.5" classname="Dashboard_Tests.Forgot_Password_Negative_Test"/>
  <testcase name="login_With_Invalid_Mobile_Number" time="5.64" classname="Dashboard_Tests.Login_Negative_Test"/>
  <testcase name="login_With_Valid_Mobile_Number" time="6.609" classname="Dashboard_Tests.Login_With_Single_User_Test"/>
  <testcase name="login_With_Valid_Mobile_Number" time="47.716" classname="Dashboard_Tests.Login_With_Multiple_Users_Data_Driven_Test"/>
  <testcase name="loginDataDriven" time="0.006" classname="Dashboard_Tests.Login_DataDriven_Through_DataProvider_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Dashboard_Tests.Login_DataDriven_Through_DataProvider_Test.loginDataDriven(Login_DataDriven_Through_DataProvider_Test.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDriven -->
  <testcase name="loginDataDriven" time="0.017" classname="Dashboard_Tests.Login_DataDriven_Through_DataProvider_Test">
    <failure type="java.lang.AbstractMethodError">
      <![CDATA[java.lang.AbstractMethodError
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDriven -->
</testsuite> <!-- Running Regression for dashboard tests -->
